name: (the_vekter)
favicon: null
layout_spectrum: 0.95961
typography_spectrum: 0.2146
title: fear of a hakd planet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000d04'
    - '#5ae200'
    - '#00a006'
    - '#485d29'
    - '#eec893'
  brandStrength: 0.44397909427061677
  lightness: 0.786732901353389
  saturation: 0.8262764089740813
  rhythmicContrast: 0.75
purpose: []
