name: the(vekter)
favicon: null
layout_spectrum: 0.95961
typography_spectrum: 0.2146
title: fear of a hakd planet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#009a7d'
    - '#010207'
    - '#ffcb00'
    - '#c6d4f9'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
